### ISSUE TITLE
Add new repository links

### ISSUE THREAD

**Issue by promaroy** [lugnitdgp/Hack-Day#139]
Append a dictionary with repo_link to the repos array in the repos.json file.

**Comment by Zubair-12** [comment]
Are these repositories still opened?

**Comment by arc9693** [comment]
With the end of hacktoberfest 2019, this issue is closed.

**Comment by Zubair-12** [comment]
Will you bring again for first time users?

**Comment by arc9693** [comment]
@Zubair-12 Yes. The website is under development and hosted [here](https://hack-day-2020.netlify.app/). Contributions for hacktoberfest 2020 will be made to 2020 branch. Feel free to contribute.
