### ISSUE TITLE
Add your profile card 

### ISSUE THREAD

**Issue by JayjeetAtGithub** [lugnitdgp/Hack-Day#15]
Add a card similar to this.

<img width="375" alt="Screenshot 2019-10-07 at 2 27 02 PM" src="https://user-images.githubusercontent.com/33978990/66298053-94656e00-e90e-11e9-8870-77b6b772cbc0.png">

**Comment by MojtabaZare** [comment]
hi @JayjeetAtGithub, I work on it.

**Comment by Sbabureddy** [comment]
May I work on it? @JayjeetAtGithub

**Comment by emrizkiem** [comment]
I would like to work on this issue. Could you assign me for this issue?

**Comment by arc9693** [comment]
With the end of hacktoberfest 2019, this issue is closed.
